### ISSUE TITLE
训练一半会出现cpu,gpu不一致的问题

### ISSUE THREAD

**Issue by lingbaishun** [taishan1994/Llama3-Finetuning#1]
RuntimeError: Expected all tensors to be on the same device, but found at  least two devices , cpu and cuda:0! 
在trainer.train()处

**Comment by taishan1994** [comment]
你启动的脚本是什么

**Comment by lingbaishun** [comment]
> 你启动的脚本是什么

NCCL_P2P_DISABLE=1 \
NCCL_IB_DISABLE=1 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
torchrun \
--nproc_per_node 8 \
--nnodes 1 \
--node_rank 0 \
--master_addr localhost \
--master_port 6601 \
../finetune_llama3.py \
--model_name_or_path "/mnt/workspace/models/Meta-Llama-3-8B-Instruct" \
--data_path "/mnt/workspace/code/Llama3-Finetuning-main/data/train.json" \
--bf16 True \
--output_dir "../output/llama3_8B_lora_test" \
--num_train_epochs 10 \
--per_device_train_batch_size 4 \
--per_device_eval_batch_size 1 \
--gradient_accumulation_steps 4 \
--evaluation_strategy "no" \
--save_strategy "steps" \
--save_steps 5 \
--save_total_limit 1 \
--learning_rate 1e-5 \
--weight_decay 0.1 \
--adam_beta2 0.95 \
--warmup_ratio 0.01 \
--lr_scheduler_type "cosine" \
--logging_steps 1 \
--report_to "none" \
--model_max_length 4096 \
--gradient_checkpointing True \
--lazy_preprocess True \
--deepspeed "../config/ds_config_zero3_72B.json" \
--use_lora

**Comment by lingbaishun** [comment]
> 你启动的脚本是什么

一开始不会报错，等训练个大半天后才会

**Comment by taishan1994** [comment]
> > 你启动的脚本是什么
> 
> 一开始不会报错，等训练个大半天后才会

把deepspeed的配置文件换成zero2或者不带72B的那个。
